### ISSUE TITLE
求助：终端输入./make_os.sh后， 终端显示  line 5: cd: src: Not a directory 。

### ISSUE THREAD

**Issue by tingjunwong** [freelw/LanOS#1]
@freelw，up主你好， 本人小白,没学多久操作系统，问题幼稚，还请见谅.。终端输入./make_os.sh后， 终端显示  line 5: cd: src: Not a directory 。github上确实 src 是文件夹， 但是  我 git clone 到本地后， 就变成了文件，请问 有什么解决的办法吗？我看了一下 make_os.sh 中  是 cd src 命令，能不能改成别的哈？   在这里谢谢up主的讲授视频啦。 b站等级不够没法提问，所以在这里问了。

对了， 小白不太懂 src 文件夹 有一个 向右箭头 表示什么意思？  恳请 各位小伙伴解答一下

**Comment by tingjunwong** [comment]
![github issue](https://user-images.githubusercontent.com/41575621/78656838-8b277f00-78fa-11ea-86aa-4a0d94e11c48.jpg)

**Comment by freelw** [comment]
可以加我qq 826231693
